
defaultTasks 'run'

apply plugin: 'java'

group 'signifiers'
version '1.0-SNAPSHOT'

sourceCompatibility = 1.8

repositories {
    mavenCentral()
    maven { url "http://jacamo.sourceforge.net/maven2" }
    maven { url "https://raw.github.com/jacamo-lang/mvn-repo/master" }
    mavenLocal()
}

dependencies {
    testCompile group: 'junit', name: 'junit', version: '4.12'
    implementation 'org.eclipse.rdf4j:rdf4j-runtime:3.6.2'
    implementation 'org.slf4j:slf4j-api:2.0.0-alpha1'
    implementation group: 'org.jacamo', name: 'jacamo', version: '0.9-SNAPSHOT'
    compile group: 'org.hyperagents', name: 'signifier-java', version: '1.0-SNAPSHOT'

    //Fom jacamo-hypermedia
    implementation 'org.apache.httpcomponents.client5:httpclient5:5.0'
    implementation 'org.apache.httpcomponents.client5:httpclient5-fluent:5.0'

    implementation 'com.google.code.gson:gson:2.11.0'

    // https://mvnrepository.com/artifact/org.eclipse.rdf4j/rdf4j-model
    implementation group: 'org.eclipse.rdf4j', name: 'rdf4j-model', version: '2.4.2'
    // https://mvnrepository.com/artifact/org.eclipse.rdf4j/rdf4j-repository-sail
    implementation group: 'org.eclipse.rdf4j', name: 'rdf4j-repository-sail', version: '2.4.2'
    // https://mvnrepository.com/artifact/org.eclipse.rdf4j/rdf4j-sail-memory
    implementation group: 'org.eclipse.rdf4j', name: 'rdf4j-sail-memory', version: '2.4.2'
}

sourceSets {
    main {
        java {
            srcDir 'src/env'
            srcDir 'src/agt'
            srcDir 'src/org'
        }
        resources {
            srcDir 'src/resources'
        }
    }
}

task run (type: JavaExec, dependsOn: 'classes') {
    group       ' JaCaMo'
    description 'runs the JaCaMo application'
    doFirst {
        mkdir 'log'
    }
    main 'jacamo.infra.JaCaMoLauncher'
    if(project.hasProperty('jcmFile')){
        args jcmFile
    } else {
        args 'sem-demo.jcm'
    }
    classpath sourceSets.main.runtimeClasspath
}